version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: kc_test
      POSTGRES_USER: kc_user
      POSTGRES_PASSWORD: kc_pass
    ports: ["5433:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kc_user -d kc_test"]
      interval: 5s
      timeout: 3s
      retries: 20
  redis:
    image: redis:7-alpine
    ports: ["6380:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: kcminio
      MINIO_ROOT_PASSWORD: kcminiopass
    ports: ["9000:9000","9001:9001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 20
  createbuckets:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set kcminio http://minio:9000 kcminio kcminiopass &&
      mc mb -p kcminio/kc-media || true &&
      mc anonymous set download kcminio/kc-media || true &&
      echo 'MinIO bucket hazır'; sleep 1"
