services:
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes: ["./backend:/app"]
    command: bash -lc "pip install -U pip && pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports: ["8000:8000"]
    environment:
      # Database
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/kurban_cebimde
      - REDIS_URL=redis://redis:6379
      
      # JWT
      - SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRE_MINUTES=60
      
      # External Services
      - LIVEKIT_URL=wss://kurban-cebimde-q2l64d9v.livekit.cloud
      - LIVEKIT_API_KEY=APIcAygxUZnX6kb
      - LIVEKIT_API_SECRET=o9orYHfogJSrt0RaAOqeSEHfSevh9wH0ArDxrmwhHTeA
      - AGORA_APP_ID=b63be89680364362ad053363645e9243
      - AGORA_APP_CERT=YOUR_AGORA_CERTIFICATE_HERE
      
      # Notification Services
      - EXPO_ACCESS_TOKEN=your_expo_access_token
      - TWILIO_ACCOUNT_SID=your_twilio_account_sid
      - TWILIO_AUTH_TOKEN=your_twilio_auth_token
      - TWILIO_PHONE_NUMBER=your_twilio_phone_number
      
      # Payment Gateways
      - IYZICO_API_KEY=your_iyzico_api_key
      - IYZICO_SECRET_KEY=your_iyzico_secret_key
      - IYZICO_BASE_URL=https://sandbox-api.iyzipay.com
      
      # Email
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your_email@gmail.com
      - SMTP_PASSWORD=your_app_password
      
      # Security
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8081
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8081
      
      # Monitoring
      - DEBUG=true
      - LOG_LEVEL=INFO
      - MAINTENANCE_MODE=false
    depends_on:
      - postgres
      - redis
    networks:
      - kurban-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=kurban_cebimde
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kurban-network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - kurban-network

  # celery:
  #   image: python:3.11-slim
  #   working_dir: /app
  #   volumes: ["./kurban-cebimde/backend:/app"]
  #   command: bash -lc "pip install -U pip && pip install celery redis psycopg2-binary && celery -A main.celery_app worker --loglevel=info"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:password@postgres:5432/kurban_cebimde
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - kurban-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
      - admin-panel
    networks:
      - kurban-network

  admin-panel:
    image: node:18-alpine
    working_dir: /app
    volumes: ["./kurban-cebimde/admin-panel:/app"]
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    ports:
      - "3001:3000"
    environment:
      - VITE_API_BASE=http://185.149.103.247:8000/api/admin/v1
      - VITE_PROXY=0
    networks:
      - kurban-network

volumes:
  postgres_data:
  redis_data:

networks:
  kurban-network:
    driver: bridge




